---
title: "Welcome to How Much Data?"
---

Welcome to *How Much Data*?, an online workshop on sample-size determination.

Here you will find:

-   [A self-paced course](Introduction.qmd) to help you gain skills with sample-size planning

-   A list of [resources](Resources.qmd) for helping you on your sample-size planning journey

-   A [blog](Blog.qmd) with updates and news relevant for sample-size planning

-   The source code for this course and website that you may use to help customize these resources for your own training purposes and programs.

This course was developed by [Bob Calin-Jageman](https://calin-jageman.net/lab/) at [Dominican University](https://www.dom.edu/directory/robert-calin-jageman). Your feedback, comments, and bug reports are very welcome – submit them via Github here.

This course has been a long time in the making and is still under active development. Expect addition of new topics (e.g. Simulation for Sample-Size Planning), additional simulations, and more.

The development of this course was supported by NIH.
