---
title: "Why You Need Sample-Size Planning"
---

{{< video https://youtu.be/_X0Alxwhvoo >}}

Why is sample-size planning so important? The short video above takes you through some extrinsic reasons (funders demand it!) and some more important intrinsic reasons (it is an ethical obligation and a key to fruitful science!).

Want to dig deeper? Here are some of the guidelines and reporting requirements mentioned:

-   NIH emphasis on rigor and reproducibility

    -   As of 2016, NIH has adopted a new initiative on [Rigor and Reproducibility](https://grants.nih.gov/reproducibility/index.htm) that stress evaluation of project proposals for their ability to produce robust and unbiased results.

    -   In explaining this new policy, sample-size planning was listed as a way to help meet this new evaluation criterion. See the NIH blog post [here](https://nexus.od.nih.gov/all/2016/01/28/scientific-rigor-in-nih-grant-applications/):

-   Reporting Guidelines -

    -   The [ARRIVE guidelines](https://arriveguidelines.org/) provide very useful advice for reporting *in vivo* experiments. It includes the requirement of reporting sample sizes clearly and justifying how they were set.

    -   The NIH also helped organize a set of principles for the reporting of pre-clinical research; these guidelines were endorsed by a wide variety of journals and professional societies. Here are the [NIH guidelines](https://www.nih.gov/research-training/rigor-reproducibility/principles-guidelines-reporting-preclinical-research). The guidelines related to transparency stipulates that authors should explain their sample-size determinations.

        -   *Nature Neuroscience* announced updated standards in [2013 editorial](https://www.nature.com/articles/nn.3391) and released a [reporting checklist](http://www.nature.com/neuro/pdf/sm_checklist.pdf) authors should complete on submission that requires sample-size planning.

        -   *Journal of Neuroscience* has issued [updated author guidelines](http://www.jneurosci.org/sites/default/files/JN_Information_for_Authors.pdf) as of March of 2017 that asks for sample-size justification.

-   Ethical considerations - the American Stasitical Association has put forth ethical guidelines for those who regularly use statistics. These enjoin statisticians to collect neither too much nor too little data (as both are ethically problematic). The guidelines are online [here](http://www.amstat.org/ASA/Your-Career/Ethical-Guidelines-for-Statistical-Practice.aspx).
